Repository ThibautHH/Arcade, pull requests merged in 2024-04, with the labels that each got.

#10 Graphics
  assets/Graphics/apple.png
  assets/Graphics/body_bottomleft.png
  assets/Graphics/body_bottomright.png
  assets/Graphics/body_horizontal.png
  assets/Graphics/body_topleft.png
  assets/Graphics/body_topright.png
  assets/Graphics/body_vertical.png
  assets/Graphics/head_down.png
  assets/Graphics/head_left.png
  assets/Graphics/head_right.png
  assets/Graphics/head_up.png
  assets/Graphics/tail_down.png
  assets/Graphics/tail_left.png
  assets/Graphics/tail_right.png
  assets/Graphics/tail_up.png
  assets/arial.ttf
  lib/Display/IDisplayModule.hpp
  lib/Display/ISprite.hpp
  lib/Display/SDL2/Makefile
  lib/Display/SDL2/Sdl.cpp
  lib/Display/SDL2/Sdl.hpp
  lib/Display/SFML/Sfml.cpp
  lib/Display/SFML/Sfml.hpp
  lib/Games/IGameModule.hpp
  lib/Games/ISprite.hpp
  lib/Games/Nibbler/Nibbler.cpp
  lib/Games/Nibbler/Nibbler.hpp
  lib/Games/Snake/Snake.cpp
  lib/Games/Snake/Snake.hpp
Labels: enhancement

#9 feat(Ncurses) Add ncurses functions
  lib/Display/NCurses/Ncurses.cpp
  lib/Display/NCurses/Ncurses.hpp
Labels: enhancement

#12 merge(core) Add base core implementation
  .github/workflows/doxygen.yml
  .gitignore
  Makefile
  README.md
  doc/.markdownlint.json
  doc/BUILD.md
  doc/Doxyfile
  doc/GAMES.md
  doc/LIBRARIES.md
  doc/USAGE.md
  doc/cppreference-doxygen-web.tag.xml
  lib/.gitignore
  lib/Display/ISprite.hpp
  lib/Display/NCurses/Makefile
  lib/Display/NCurses/Ncurses.cpp
  lib/Display/SDL2/Makefile
  lib/Display/SDL2/Sdl.cpp
  lib/Display/SDL2/Sdl.hpp
  lib/Display/SFML/Makefile
  lib/Display/SFML/Sfml.cpp
  lib/Display/SFML/Sfml.hpp
  lib/Games/IGameModule.hpp
  lib/Games/ISprite.hpp
  lib/Games/Nibbler/Makefile
  lib/Games/Nibbler/Nibbler.cpp
  lib/Games/Nibbler/Nibbler.hpp
  lib/Games/Snake/Makefile
  lib/Games/Snake/Snake.cpp
  lib/Games/Snake/Snake.hpp
  src/Core/Core.cpp
  src/Core/Core.hpp
  src/Core/DynamicLibrary.cpp
  src/Core/DynamicLibrary.hpp
  src/Core/ModuleLibrary.cpp
  src/Core/ModuleLibrary.hpp
  src/Core/Processor.cpp
  src/Core/Processor.hpp
  src/Displays/Sprite.hpp
Labels: enhancement

#13 feat(core) Add symbol specification in ModuleLibrary
  src/Core/ModuleLibrary.cpp
  src/Core/ModuleLibrary.hpp
  src/Core/Processor.hpp
Labels: enhancement

#14 merge(menu) Add menu module and logic
  .gitignore
  Makefile
  src/Core/Menu.cpp
  src/Core/Menu.hpp
  src/Core/ModuleLibrary.cpp
  src/Core/ModuleLibrary.hpp
  src/Core/Processor.cpp
  src/Core/Processor.hpp
Labels: enhancement

#15 ci(doxygen) Fix deployment action
  .github/workflows/doxygen.yml
Labels: bug, ci

#16 fix(core) Delete modules before unloading libraries
  src/Core/Processor.cpp
Labels: bug

#17 merge(graphics) Fix and finish libraries for a working menu
  assets/Graphics/Body.png
  assets/Graphics/Tail.png
  assets/Graphics/Wall.png
  assets/Maps/map1.txt
  assets/Maps/map2.txt
  assets/Maps/map3.txt
  lib/Display/NCurses/Ncurses.cpp
  lib/Display/NCurses/Ncurses.hpp
  lib/Display/SDL2/Makefile
  lib/Display/SDL2/Sdl.cpp
  lib/Display/SDL2/Sdl.hpp
  lib/Display/SFML/Makefile
  lib/Display/SFML/Sfml.cpp
  lib/Display/SFML/Sfml.hpp
  lib/Games/Nibbler/Makefile
  lib/Games/Nibbler/Nibbler.cpp
  lib/Games/Nibbler/Nibbler.hpp
  lib/Games/Snake/Makefile
  lib/Games/Snake/Snake.cpp
  lib/Games/Snake/Snake.hpp
Labels: bug, enhancement

#18 feat(core) Add steady_clock ticking in core
  src/Core/Processor.cpp
Labels: enhancement

#20 fix(SFML) display text and window creation
  lib/Display/SFML/Makefile
  lib/Display/SFML/Sfml.cpp
  lib/Display/SFML/Sfml.hpp
Labels: enhancement

#21 fix(core) Propagate null Games::ISprite to the IDisplayModule
  src/Core/Processor.cpp
Labels: bug

#22 fix(core) Fix updateTile call loop
  src/Core/Processor.cpp
  src/Core/Processor.hpp
Labels: bug

#24 Snake
  Makefile
  assets/Graphics/body.png
  assets/Graphics/tail.png
  assets/background.png
  lib/Display/SDL2/Sdl.cpp
  lib/Display/SDL2/Sdl.hpp
  lib/Display/SFML/Makefile
  lib/Display/SFML/Sfml.cpp
  lib/Display/SFML/Sfml.hpp
  lib/Games/Nibbler/Nibbler.cpp
  lib/Games/Nibbler/Nibbler.hpp
  lib/Games/Snake/Makefile
  lib/Games/Snake/Snake.cpp
  lib/Games/Snake/Snake.hpp
  lib/Games/Snake/Snakemvt.cpp
  lib/Games/Snake/Snakemvt.hpp
Labels: enhancement

#25 Ncurses
  lib/Display/NCurses/Ncurses.cpp
  lib/Display/NCurses/Ncurses.hpp
Labels: bug, enhancement

#26 Sfml
  lib/Display/SFML/Sfml.cpp
  lib/Display/SFML/Sfml.hpp
Labels: bug, enhancement

#28 doc(Readme) Add usage instructions and implementation guide for new g…
  README.md
  doc/IMPLEMENT.md
Labels: documentation

#29 doc(Readme) Add key bindings to README.md
  README.md
Labels: documentation

#30 feat(Snake) Update SFML display and Snake game logic
  lib/Display/SFML/Sfml.cpp
  lib/Display/SFML/Sfml.hpp
  lib/Games/Snake/Snake.cpp
  lib/Games/Snake/Snake.hpp
  lib/Games/Snake/Snakemvt.cpp
  lib/Games/Snake/Snakemvt.hpp
Labels: enhancement

#32 feat(Games): fix sdl clock
  lib/Display/SDL2/Sdl.cpp
  lib/Games/Nibbler/Nibbler.cpp
  lib/Games/Nibbler/Nibblermvt.cpp
  lib/Games/Snake/Snake.cpp
  lib/Games/Snake/Snakemvt.cpp
Labels: bug

#33 merge(menu) Name changing UI feature
  src/Core/Menu.cpp
  src/Core/Menu.hpp
  src/Core/Processor.cpp
Labels: enhancement

#34 merge(core) Add special display inputs handling
  src/Core/Menu.cpp
  src/Core/Menu.hpp
  src/Core/Processor.cpp
  src/Core/Processor.hpp
Labels: enhancement

#36 bug(sdl2) Bad handling of PREV_LIB and NEXT_LIB key types #35
  lib/Display/SDL2/Sdl.cpp
Labels: bug

#37 merge(core) Optimize and simplify menu instance management
  src/Core/Menu.cpp
  src/Core/Menu.hpp
  src/Core/Processor.cpp
  src/Core/Processor.hpp
Labels: bug

#38 build(Makefile) Add core recipe
  Makefile
Labels: enhancement
